### PR TITLE
[SIS-114] Text module fixes

### LINKED ISSUE #114: [SIS-114] Tapping LP Editor text box and module brings up keyboard
- [x] Currently, for the `ContentCard` component and `StoredContent` in the LP editor, you need to tap near where the text is for the keyboard to pull up. It's a very small and specific area to tap. You should be able to tap on the entire box itself.

**Current behaviour:**
Can only click on 'Lorem ipsum...' text for the keyboard to pull up. Tapping on border or where there's no text doesn't do anything. 
Image

Tapping on blue box does nothing. Need to tap on "Add text here." to pull up keyboard.
Image

- [x] Remove `LessonPlanTextField` if it's not being used anywhere (lost component)

### PR DESCRIPTION
**Pull request by ramyzhang**
# Description

- [x] Fix issue where you can only tap on the text to focus the TextInput component, but not the whole text module content container

Ticket #114 and #92

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] My PR title is formatted as [SIS-\<issue number\>] \<issue name\> (eg. [SIS-010] Create UI button)
- [x] I have linked my issue/ticket on the project board to this PR
- [x] I have sent my PR to #team-sistema-prs on Slack and requested two people to review
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (if required)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

File: src/editor/components/LessonSection.js [hunk 1]
```diff
@@ -36,17 +38,6 @@ const LessonSection = ({ sectionType, subtitle, navigation }) => {
           placeholder={'Input text'}
           handleClick={handleClick}
         />
-        {/* <TouchableOpacity
```
Comment (Lemiex) [inline src/editor/components/LessonSection.js:39]: Thanks for deleting this!

**Review by Lemiex — APPROVED** [review]
Looks good! Looks like you wrapped things in a TouchableOpactiy, which makes sense👍🏼

**Review by MinGi-K — APPROVED** [review]
LGTM!! I didn't know you can use ref prop like that for textinput, really interesting!
